{% set version = "0.12.0" %}

package:
  name: delocate
  version: {{ version }}

source:
  fn: delocate-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/delocate/delocate-{{ version }}.tar.gz
  sha256: e051660836a87b61c99b9b180344be363c31e1f2d9fdc94caebc854b6611335c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - packaging
    - typing-extensions
    - macholib

test:
  imports:
    - delocate
  commands:
    - delocate-listdeps -h
    - delocate-wheel -h

about:
  home: https://github.com/matthew-brett/delocate
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Move OSX dynamic libraries into package

extra:
  recipe-maintainers:
    - jschueller
    - isuruf
