appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: hQi3xs1va6+7mrnZGzso0DwYSJyLgd1YTjn+FhC7S3Z4JAlH57PEKgcyfRNlS5R9jrYCJn4DE1JpEjOudnShdTdAUrOoRIrgomEbRTc0LladjO/2I8k12NJ7CvwOAcJjDd5Y3aEjsl4JoyWLzcw44Z2S+WdKCtrvab7yPwjYiC/QYY+2rBgOMJrGLjIVUbbPf+MTgQwLsm4M9cbSyjFO4bUpMS7acuxyO8R0hpJd91FigTNK0lBAi5Ud0d6IvmhNv9wJOrogsVZdypGprKPYuQF/0In3hpZfRbX/HR7z/Rg6ytFZNbZ6I/Cef7ZX9cfZJPfKm/60Q332pexr2OoFmp/OlyaHCkHBN9WzMdUBxJ4Unm9aXEGOxKLBe4njCfsWTKVBl1b+hIaeuYBQaGnAwxb/bxgh13xv/+Ch4GaK7VAnHcIiEHAwimDtnu1Diu58xwJR95u5c9oXDsdSFfLsVLrpKXKpWLw/yqovJoXNoS0egfaj4cZEr02n7q0jUWX4N03ypINvvAebr2PJuBswmGfIaKVIEEs9AdN1mb8p+YC0tHnW9fmDuDcpXm4mp9vKtgKQw/Zy6YWifS9fquCglpgiIwIFXkfSowAJb7LM2b9NybNiFO6J/oGJj13cRAGKH5ZBBb2V/ilpYuS1HMJfPNX8peUBwv1Buk51jRPgENU=}
conda_forge_output_validation: true
